spring:
  profiles:
    active: local
    include: jwt, datasource
  application:
    name: was
  main:
    banner-mode: off
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 9090