---
spring:
  config:
    activate:
      on-profile: local, test

webclient:
  serviceProperties:
    - service: AGGREGATION
      #          base-url: http://13.209.128.251:8080
      base-url: http://localhost:9091
      read-timeout: 5000
      write-timeout: 5000
      connection-timeout: 5000
      max-connections: 60
      pending-acquire-max-count: 120
      pending-acquire-timeout: 10000
      max-idle-time: 60